version: '3'

services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
